"""cut.jianying.pro_color — 专业调色 LUT 生成器。

基于剪映/达芬奇大神调色调研：
- 青橙电影感 / 赛博朋克 / 日系电影感 / 小清新 / 黑金质感 / 复古胶片 / 莫兰迪

提供两种实现：
1. 生成 .cube LUT 文件（3D LUT，可导入剪映/PR/达芬奇）
2. 直接在 draft 中应用调色（通过 effect material）
"""
from __future__ import annotations

import os
from pathlib import Path
from typing import Optional, Dict, Any, List

from .draft import Draft, _new_id


COLOR_PRESETS = {
    "teal_orange": {
        "name": "青橙电影感", "name_en": "Teal & Orange Cinematic",
        "description": "阴影偏青，高光偏橙，肤色保持自然",
        "shadows_hue_shift": 15, "shadows_saturation": 1.3, "shadows_luminance": -0.05,
        "midtones_hue_shift": 0, "midtones_saturation": 1.1, "midtones_luminance": 0,
        "highlights_hue_shift": -15, "highlights_saturation": 1.4, "highlights_luminance": 0.05,
        "contrast": 1.15, "temperature": 0.1, "tint": 0.0, "vignette": 0.3,
    },
    "cyberpunk": {
        "name": "赛博朋克", "name_en": "Cyberpunk Neon",
        "description": "低亮度高饱和，冷蓝紫主导 + 霓虹粉点缀",
        "shadows_hue_shift": -20, "shadows_saturation": 1.6, "shadows_luminance": -0.15,
        "midtones_hue_shift": -10, "midtones_saturation": 1.4, "midtones_luminance": -0.05,
        "highlights_hue_shift": 25, "highlights_saturation": 1.8, "highlights_luminance": 0.1,
        "contrast": 1.3, "temperature": -0.2, "tint": 0.15, "vignette": 0.4,
    },
    "japanese_film": {
        "name": "日系电影感", "name_en": "Japanese Film",
        "description": "低对比，偏青绿，整体柔和淡雅",
        "shadows_hue_shift": 10, "shadows_saturation": 0.8, "shadows_luminance": 0.05,
        "midtones_hue_shift": 5, "midtones_saturation": 0.85, "midtones_luminance": 0.05,
        "highlights_hue_shift": -5, "highlights_saturation": 0.8, "highlights_luminance": 0.1,
        "contrast": 0.9, "temperature": -0.05, "tint": 0.05, "vignette": 0.15,
    },
    "fresh": {
        "name": "小清新", "name_en": "Fresh & Bright",
        "description": "提亮，降饱和，暖偏，适合人像美食",
        "shadows_hue_shift": 0, "shadows_saturation": 0.85, "shadows_luminance": 0.1,
        "midtones_hue_shift": 0, "midtones_saturation": 0.9, "midtones_luminance": 0.08,
        "highlights_hue_shift": -5, "highlights_saturation": 0.85, "highlights_luminance": 0.05,
        "contrast": 0.9, "temperature": 0.15, "tint": 0.05, "vignette": 0.0,
    },
    "black_gold": {
        "name": "黑金质感", "name_en": "Black & Gold",
        "description": "黑色 + 金色双色调，奢华质感",
        "shadows_hue_shift": 0, "shadows_saturation": 0.3, "shadows_luminance": -0.2,
        "midtones_hue_shift": -25, "midtones_saturation": 1.3, "midtones_luminance": 0,
        "highlights_hue_shift": -30, "highlights_saturation": 1.5, "highlights_luminance": 0.1,
        "contrast": 1.25, "temperature": 0.2, "tint": -0.05, "vignette": 0.35,
    },
    "vintage_film": {
        "name": "复古胶片", "name_en": "Vintage Film",
        "description": "褪色效果，偏黄绿，模拟老胶片",
        "shadows_hue_shift": 10, "shadows_saturation": 0.7, "shadows_luminance": 0.08,
        "midtones_hue_shift": 8, "midtones_saturation": 0.75, "midtones_luminance": 0.03,
        "highlights_hue_shift": -10, "highlights_saturation": 0.8, "highlights_luminance": -0.05,
        "contrast": 0.85, "temperature": 0.18, "tint": 0.08, "vignette": 0.4, "grain": 0.15,
    },
    "morandi": {
        "name": "莫兰迪", "name_en": "Morandi Tones",
        "description": "低饱和灰调，高级感配色",
        "shadows_hue_shift": 5, "shadows_saturation": 0.6, "shadows_luminance": 0.05,
        "midtones_hue_shift": 0, "midtones_saturation": 0.65, "midtones_luminance": 0.03,
        "highlights_hue_shift": -5, "highlights_saturation": 0.6, "highlights_luminance": 0.05,
        "contrast": 0.88, "temperature": 0.05, "tint": 0.0, "vignette": 0.1,
    },
}


def generate_cube_lut(preset, output_path, size=32):
    """生成 .cube 3D LUT 文件。"""
    if preset not in COLOR_PRESETS:
        raise KeyError(f"未知调色预设: {preset}. 可选: {list(COLOR_PRESETS)}")

    cfg = COLOR_PRESETS[preset]
    lines = [
        f"TITLE \"{cfg['name_en']}\"",
        f"LUT_3D_SIZE {size}",
        "DOMAIN_MIN 0.0 0.0 0.0",
        "DOMAIN_MAX 1.0 1.0 1.0",
        "",
        f"# Generated by cut.skill - {cfg['name']} ({cfg['description']})",
    ]

    for b in range(size):
        for g in range(size):
            for r in range(size):
                r_val = r / (size - 1)
                g_val = g / (size - 1)
                b_val = b / (size - 1)
                r_out, g_out, b_out = _apply_color_transform(r_val, g_val, b_val, cfg)
                r_out = max(0.0, min(1.0, r_out))
                g_out = max(0.0, min(1.0, g_out))
                b_out = max(0.0, min(1.0, b_out))
                lines.append(f"{r_out:.6f} {g_out:.6f} {b_out:.6f}")

    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    return {"preset": preset, "name": cfg["name"], "output_path": output_path,
            "size": size, "data_points": size ** 3}


def _apply_color_transform(r, g, b, cfg):
    """对一个 RGB 像素应用调色变换。"""
    lum = 0.2126 * r + 0.7152 * g + 0.0722 * b

    if lum < 0.33:
        weights = (1.0, 0.0, 0.0)
    elif lum < 0.66:
        weights = (0.0, 1.0, 0.0)
    else:
        weights = (0.0, 0.0, 1.0)

    s_hue = cfg["shadows_hue_shift"] / 360.0
    s_sat = cfg["shadows_saturation"]
    s_lum = cfg["shadows_luminance"]
    m_hue = cfg["midtones_hue_shift"] / 360.0
    m_sat = cfg["midtones_saturation"]
    m_lum = cfg["midtones_luminance"]
    h_hue = cfg["highlights_hue_shift"] / 360.0
    h_sat = cfg["highlights_saturation"]
    h_lum = cfg["highlights_luminance"]

    hue_shift = s_hue * weights[0] + m_hue * weights[1] + h_hue * weights[2]
    sat_mult = s_sat * weights[0] + m_sat * weights[1] + h_sat * weights[2]
    lum_adj = s_lum * weights[0] + m_lum * weights[1] + h_lum * weights[2]

    h, s, v = _rgb_to_hsv(r, g, b)
    h = (h + hue_shift) % 1.0
    s = max(0, min(1, s * sat_mult))
    v = max(0, min(1, v + lum_adj))

    contrast = cfg.get("contrast", 1.0)
    v = max(0, min(1, (v - 0.5) * contrast + 0.5))

    temp = cfg.get("temperature", 0.0)
    r_new = r + temp * 0.1
    b_new = b - temp * 0.1

    tint = cfg.get("tint", 0.0)
    r_new += tint * 0.05
    b_new += tint * 0.05
    g_new = g - tint * 0.05

    r_out, g_out, b_out = _hsv_to_rgb(h, s, v)
    r_out = (r_out + r_new) / 2
    g_out = (g_out + g_new) / 2
    b_out = (b_out + b_new) / 2

    return r_out, g_out, b_out


def _rgb_to_hsv(r, g, b):
    mx = max(r, g, b)
    mn = min(r, g, b)
    diff = mx - mn
    if diff == 0:
        h = 0
    elif mx == r:
        h = ((g - b) / diff) % 6
    elif mx == g:
        h = (b - r) / diff + 2
    else:
        h = (r - g) / diff + 4
    h /= 6
    s = 0 if mx == 0 else diff / mx
    v = mx
    return h, s, v


def _hsv_to_rgb(h, s, v):
    if s == 0:
        return v, v, v
    h = h * 6
    i = int(h)
    f = h - i
    p = v * (1 - s)
    q = v * (1 - s * f)
    t = v * (1 - s * (1 - f))
    i = i % 6
    if i == 0: return v, t, p
    if i == 1: return q, v, p
    if i == 2: return p, v, t
    if i == 3: return p, q, v
    if i == 4: return t, p, v
    return v, p, q


def apply_color_preset(draft, segment_id, preset, intensity=1.0):
    """在 draft 中给 segment 应用调色预设。"""
    if preset not in COLOR_PRESETS:
        raise KeyError(f"未知调色预设: {preset}. 可选: {list(COLOR_PRESETS)}")

    cfg = COLOR_PRESETS[preset]
    target_seg = draft.get_segment_raw(segment_id)
    if not target_seg:
        raise KeyError(f"segment {segment_id} 不存在")

    color_fx_id = _new_id()
    color_fx = {
        "id": color_fx_id, "type": "effect",
        "resource_id": f"effect.color_grade.{preset}",
        "name": cfg["name"], "name_en": cfg["name_en"],
        "category_name": "color_grade",
        "is_affect_video": True, "is_affect_audio": False,
        "is_valid": True, "intensity": intensity,
        "params": {
            "contrast": cfg["contrast"], "temperature": cfg["temperature"],
            "tint": cfg["tint"],
            "shadows_hue": cfg["shadows_hue_shift"],
            "shadows_saturation": cfg["shadows_saturation"],
            "shadows_luminance": cfg["shadows_luminance"],
            "midtones_hue": cfg["midtones_hue_shift"],
            "midtones_saturation": cfg["midtones_saturation"],
            "midtones_luminance": cfg["midtones_luminance"],
            "highlights_hue": cfg["highlights_hue_shift"],
            "highlights_saturation": cfg["highlights_saturation"],
            "highlights_luminance": cfg["highlights_luminance"],
            "vignette": cfg.get("vignette", 0),
        },
    }
    draft.add_material("effect", color_fx)

    refs = target_seg.setdefault("extra_material_refs", [])
    refs.append(color_fx_id)
    draft._modified = True

    if cfg.get("vignette", 0) > 0:
        try:
            from .effects import add_video_effect
            add_video_effect(draft, segment_id, preset="vignette", intensity=cfg["vignette"])
        except Exception:
            pass

    return {"color_effect_id": color_fx_id, "preset": preset,
            "name": cfg["name"], "intensity": intensity}


def apply_color_preset_to_all(draft, preset, intensity=1.0, track_id=None):
    """批量给所有视频 segment 应用调色预设。"""
    results = []
    for track in draft.video_tracks:
        if track_id and track.id != track_id:
            continue
        for seg in track.segments:
            try:
                r = apply_color_preset(draft, seg.id, preset, intensity)
                results.append(r)
            except Exception as e:
                results.append({"error": str(e), "segment_id": seg.id})
    return {"applied": len([r for r in results if "color_effect_id" in r]),
            "preset": preset, "results": results}


def generate_all_luts(output_dir, size=32):
    """生成所有调色预设的 .cube 文件到指定目录。"""
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    generated = []
    for preset_key in COLOR_PRESETS:
        out = output_dir / f"{preset_key}.cube"
        try:
            r = generate_cube_lut(preset_key, str(out), size)
            generated.append(r)
        except Exception as e:
            generated.append({"preset": preset_key, "error": str(e)})

    readme_path = output_dir / "README.md"
    with open(readme_path, "w", encoding="utf-8") as f:
        f.write("# cut.skill 调色 LUT 包\n\n")
        f.write("本目录由 cut.skill 自动生成，包含以下调色预设：\n\n")
        for key, cfg in COLOR_PRESETS.items():
            f.write(f"## {cfg['name']} ({key})\n")
            f.write(f"{cfg['description']}\n\n")
            f.write(f"文件: `{key}.cube`\n\n")
        f.write("\n## 使用方法\n\n")
        f.write("### 剪映\n1. 滤镜 → 导入 LUT\n2. 选择对应的 .cube 文件\n3. 调整强度（建议 50-80%）\n\n")
        f.write("### Premiere Pro\n1. Lumetri Color → 创意 → Look\n2. 浏览 → 选择 .cube 文件\n\n")
        f.write("### 达芬奇\n1. LUT 库 → 右键 → 刷新\n2. 把 .cube 文件复制到达芬奇 LUT 目录\n")

    return {"output_dir": str(output_dir), "generated": len(generated),
            "files": [g.get("output_path", "") for g in generated if "output_path" in g],
            "readme": str(readme_path)}
